FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.21-openshift-4.17 AS builder
WORKDIR /src/kubevirt-csi-driver
COPY . .
RUN make build

FROM registry.ci.openshift.org/ocp/4.17:base-rhel9

LABEL io.openshift.release.operator=true
LABEL description="KubeVirt CSI Driver"

RUN yum install -y e2fsprogs xfsprogs && yum clean all
COPY --from=builder /src/kubevirt-csi-driver/kubevirt-csi-driver .

ENTRYPOINT ["./kubevirt-csi-driver"]
